name: HRRR-AWS-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyter-book
  - jupyterlab
  - dask
  - metpy
  - zarr
  - s3fs
  - sphinx-pythia-theme
  - mystmd
  - nodejs
